/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationView,
  IReputationViewInterface,
} from "../../../contracts/CreditEngine.sol/IReputationView";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "viewScore",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IReputationView__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationViewInterface {
    return new Interface(_abi) as IReputationViewInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationView {
    return new Contract(address, _abi, runner) as unknown as IReputationView;
  }
}
