/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEASLike,
  IEASLikeInterface,
} from "../../../contracts/ValidatorMarket.sol/IEASLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "uid",
        type: "bytes32",
      },
    ],
    name: "revoke",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEASLike__factory {
  static readonly abi = _abi;
  static createInterface(): IEASLikeInterface {
    return new Interface(_abi) as IEASLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IEASLike {
    return new Contract(address, _abi, runner) as unknown as IEASLike;
  }
}
