/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ReputationGraph,
  ReputationGraphInterface,
} from "../../../contracts/ReputationGraph.sol/ReputationGraph";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "validatorMarket_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "newScore",
        type: "int256",
      },
    ],
    name: "ScoreUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "agentScore",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "int256",
        name: "delta",
        type: "int256",
      },
    ],
    name: "updateScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "validatorMarket",
    outputs: [
      {
        internalType: "contract IValidatorMarketView",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "viewScore",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b506040516102da3803806102da83398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b60805161025061008a600039600060a701526102506000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80637f3d7ffa14610051578063db230b5214610066578063e35bf37c146100a2578063e6aae0a0146100e1575b600080fd5b61006461005f366004610198565b610101565b005b61008f6100743660046101c2565b6001600160a01b031660009081526020819052604090205490565b6040519081526020015b60405180910390f35b6100c97f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b039091168152602001610099565b61008f6100ef3660046101c2565b60006020819052908152604090205481565b6001600160a01b0382166000908152602081905260408120546101259083906101e4565b6001600160a01b03841660008181526020818152604091829020849055905183815292935090917f6848b28f5894c1e6a76337d595b84d08890450256bfb2a4d941f8f7f2bb33c65910160405180910390a2505050565b80356001600160a01b038116811461019357600080fd5b919050565b600080604083850312156101ab57600080fd5b6101b48361017c565b946020939093013593505050565b6000602082840312156101d457600080fd5b6101dd8261017c565b9392505050565b808201828112600083128015821682158216171561021257634e487b7160e01b600052601160045260246000fd5b50509291505056fea264697066735822122040e0ee7a233ea2ac9c92cd316a1b3d2f9458fdfe6340367cef5bd6080147b5fa64736f6c63430008180033";

type ReputationGraphConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReputationGraphConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReputationGraph__factory extends ContractFactory {
  constructor(...args: ReputationGraphConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    validatorMarket_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(validatorMarket_, overrides || {});
  }
  override deploy(
    validatorMarket_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(validatorMarket_, overrides || {}) as Promise<
      ReputationGraph & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReputationGraph__factory {
    return super.connect(runner) as ReputationGraph__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReputationGraphInterface {
    return new Interface(_abi) as ReputationGraphInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReputationGraph {
    return new Contract(address, _abi, runner) as unknown as ReputationGraph;
  }
}
