/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEAS,
  IEASInterface,
} from "../../../contracts/WorkReceiptV2.sol/IEAS";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "uid",
        type: "bytes32",
      },
    ],
    name: "isAttestationValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEAS__factory {
  static readonly abi = _abi;
  static createInterface(): IEASInterface {
    return new Interface(_abi) as IEASInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IEAS {
    return new Contract(address, _abi, runner) as unknown as IEAS;
  }
}
