/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPaymentGatewayV2,
  IPaymentGatewayV2Interface,
} from "../../../contracts/WorkReceiptV2.sol/IPaymentGatewayV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "pid",
        type: "bytes32",
      },
    ],
    name: "payments",
    outputs: [
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiry",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "settled",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "refunded",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPaymentGatewayV2__factory {
  static readonly abi = _abi;
  static createInterface(): IPaymentGatewayV2Interface {
    return new Interface(_abi) as IPaymentGatewayV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPaymentGatewayV2 {
    return new Contract(address, _abi, runner) as unknown as IPaymentGatewayV2;
  }
}
